### ISSUE TITLE
Face-Recognition

### ISSUE THREAD

**Issue by maxkor** [maxmlr/rpi-photobooth#19]
Detect Faces through live Pi cam. This feature can trigger the camera with certain symbols, group same faces in the gallery, and play a game of which face took pictures with how many other people. It can also show pictures of the face in front of it in the gallery.

**Comment by maxmlr** [comment]
Added in a simple however functional version in 3997ae00795e730a43136bf1846326ac39297682

**Comment by maxmlr** [comment]
Fully functional with 70727a2d8f088a9df4e37ab3a073c1c4d6290c0f
