### ISSUE TITLE
frame selection

### ISSUE THREAD

**Issue by maxkor** [maxmlr/rpi-photobooth#27]
frame selection does not appear to work. I have selected several frames but could see no effect in preview, taken picture or gallery view .. does frame have any effect?

**Comment by maxmlr** [comment]
yes it should, I will check

**Comment by maxmlr** [comment]
fixded in bbb8b1514bb6e5cdd313ae2db9b0f3316878ce91
you have to run tow updates:
`photobooth-update`
and then
`photobooth-update photobooth-web 2.1.0 2.1.0`
