### ISSUE TITLE
can not switch to diet pi terminal

### ISSUE THREAD

**Issue by maxkor** [maxmlr/rpi-photobooth#28]
new update works perfectly with photbooth. however if i exit Photo Booth kiosk mode with ctrl + w or ctrl + f4 I only see a black screen - is that normal - did I do something wrong?

**Comment by maxmlr** [comment]
this is intended, as tty1 is disabled. switch to tty2-x uwing:

strg + alt(option) + F[2-x]

or

alt(option) + cmd + arrow-left|arrow-right
