### ISSUE TITLE
Printer MITSUBISHI CP D80 DW

### ISSUE THREAD

**Issue by maxadler88** [maxmlr/rpi-photobooth#52]
Printer Mitsubishi CPD80 must be connected as a printer to Photo Booth.

**Comment by maxmlr** [comment]
solved based on [peachyphotos howto] (https://www.peachyphotos.com/blog/posts/201610061508-mitsubishi-cp-d70-family-working/)
(`app-get install libusb-dev`)
(`app-get install libusb-1.0-0-dev`)
`apt-get install -y pkg-config`
`apt-get install libusb-1.0-0-dev libcups2-dev libgutenprint-dev`

**Comment by maxmlr** [comment]
additional installation notes:
https://forums.raspberrypi.com/viewtopic.php?t=194147
https://sourceforge.net/p/gimp-print/discussion/134458/thread/276be56a/
https://raspberrytips.com/install-printer-raspberry-pi/
https://git.shaftnet.org/cgit/selphy_print.git/
https://www.raspberry-pi-geek.com/Archive/2016/20/Print-with-shell-commands-courtesy-of-CUPS
https://www.elektronik-kompendium.de/sites/raspberry-pi/2007081.htm
